services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    tty: true
    stdin_open: true
  redis:
    image: redis:latest
    container_name: redis_container
    env_file: .env
    ports:
      - "6380:6379"
    volumes:
      - ./redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "$REDIS_PASSWORD", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    tty: true
    stdin_open: true
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog_container
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    restart: always