services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 30s
      timeout: 10s
      retries: 1
    restart: always
    tty: true
    stdin_open: true
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-container
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always