postgres:
  context_cancel_seconds: 3
  port: 5432
  host: postgres
app:
  host: 0.0.0.0
  port: 8080
  default_per_page: 20
  default_page: 1
  max_per_page: 100
redis:
  context_cancel_seconds: 3
  key_expiration_seconds: 60
  host: redis
  port: 6379